SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

--
-- Database: `bddCake`
--
CREATE DATABASE IF NOT EXISTS `bddJdr` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `bddJdr`;


CREATE TABLE IF NOT EXISTS personnages (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  nom VARCHAR(255) NULL,
  prenom VARCHAR(255) NULL,
  race VARCHAR(255) NULL,
  type_campagne VARCHAR(255) NULL,
  age INT UNSIGNED NULL,
  profession VARCHAR(255) NULL,
  physique INT UNSIGNED NULL,
  adresse INT UNSIGNED NULL,
  social INT UNSIGNED NULL,
  esprit INT UNSIGNED NULL,
  pv INT UNSIGNED NULL,
  pv_max INT UNSIGNED NULL,
  pm INT UNSIGNED NULL,
  pm_max INT UNSIGNED NULL,
  pa INT UNSIGNED NULL,
  pi INT UNSIGNED NULL,
  ca INT UNSIGNED NULL,
  destin INT UNSIGNED NULL,
  archetype VARCHAR(255) NULL,
  gold INT UNSIGNED NULL,
  argent INT UNSIGNED NULL,
  bronze INT UNSIGNED NULL,
  niveau INT UNSIGNED NULL,
  experience INT UNSIGNED NULL,
  PRIMARY KEY(id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS competences (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  nom VARCHAR(255) NULL,
  PRIMARY KEY(id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS speciales (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  nom VARCHAR(255) NULL,
  description TEXT NULL,
  PRIMARY KEY(id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS ecoles (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  nom VARCHAR(255) NULL NOT NULL,
  description TEXT NULL NOT NULL,
  PRIMARY KEY(id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS users (
  login VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  email VARCHAR(255) NULL,
  PRIMARY KEY(login)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS objects (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  personnages_id INT UNSIGNED NOT NULL,
  nom VARCHAR(255) NULL,
  quantite INT UNSIGNED NULL,
  description TEXT NULL,
  PRIMARY KEY(id),
  INDEX objects_FKIndex1(personnages_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS familiers (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  personnages_id INT UNSIGNED NOT NULL,
  nom VARCHAR(255) NULL,
  pv INT UNSIGNED NULL,
  pv_max INT UNSIGNED NULL,
  attaque VARCHAR(255) NULL,
  special TEXT NULL,
  PRIMARY KEY(id),
  INDEX familiers_FKIndex1(personnages_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS montures (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  personnages_id INT UNSIGNED NOT NULL,
  nom VARCHAR(255) NULL,
  pv INT UNSIGNED NULL,
  pv_max INT UNSIGNED NULL,
  attaque TEXT NULL,
  special TEXT NULL,
  PRIMARY KEY(id),
  INDEX familiers_FKIndex1(personnages_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS armures (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  personnages_id INT UNSIGNED NOT NULL,
  emplacement VARCHAR(255) NULL,
  nom VARCHAR(255) NULL,
  indice FLOAT UNSIGNED NULL,
  charge INT UNSIGNED NULL,
  charge_max INT UNSIGNED NULL,
  dura INT UNSIGNED NULL,
  PRIMARY KEY(id),
  INDEX armures_FKIndex1(personnages_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS armes (
  personnages_id INT UNSIGNED NOT NULL,
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  nom VARCHAR(255) NULL,
  porte VARCHAR(255) NULL,
  degat VARCHAR(255) NULL,
  munition VARCHAR(255) NULL,
  cdt INT UNSIGNED NULL,
  dura INT UNSIGNED NULL,
  composante VARCHAR(255) NULL,
  PRIMARY KEY(id),
  INDEX equipements_FKIndex1(personnages_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS connaissances (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  competences_id INT UNSIGNED NOT NULL,
  personnages_id INT UNSIGNED NOT NULL,
  bonnus INT UNSIGNED NULL,
  PRIMARY KEY(id),
  INDEX connaissances_FKIndex1(personnages_id),
  INDEX connaissances_FKIndex2(competences_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS maitrises (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  ecoles_id INT UNSIGNED NOT NULL,
  personnages_id INT UNSIGNED NOT NULL,
  type VARCHAR(255) NOT NULL,
  PRIMARY KEY(id),
  INDEX connaissances_FKIndex1(personnages_id),
  INDEX connaissances_FKIndex2(ecoles_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS specialites (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  speciales_id INT UNSIGNED NOT NULL,
  personnages_id INT UNSIGNED NOT NULL,
  PRIMARY KEY(id),
  INDEX connaissances_FKIndex1(personnages_id),
  INDEX connaissances_FKIndex2(speciales_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;